//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_QuanLyNhaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class BILL
    {
        public int MABILL { get; set; }
        public int MAKH { get; set; }
        public int SOBAN { get; set; }
        public int MANV { get; set; }
        public int MAOD { get; set; }
        public int SOLUONGKHACH { get; set; }
        public System.DateTime CHECKIN { get; set; }
        public System.DateTime CHECKOUT { get; set; }
    
        public virtual BANAN BANAN { get; set; }
        public virtual KHACHHANG KHACHHANG { get; set; }
        public virtual NHANVIEN NHANVIEN { get; set; }
        public virtual ORDER ORDER { get; set; }
    }
}
