//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_QuanLyNhaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class CTPHIEUNHAP
    {
        public int MAPN { get; set; }
        public int MAMH { get; set; }
        public int SLNHAP { get; set; }
    
        public virtual MATHANG MATHANG { get; set; }
        public virtual PHIEUNHAP PHIEUNHAP { get; set; }
    }
}
