//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_QuanLyNhaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class HANG_TON_NHAP
    {
        public int MAMH { get; set; }
        public string TENMH { get; set; }
        public int SOLUONG { get; set; }
        public int SLNHAP { get; set; }
    }
}
