//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_QuanLyNhaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MATHANG
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MATHANG()
        {
            this.CTPHIEUNHAPs = new HashSet<CTPHIEUNHAP>();
        }
    
        public int MAMH { get; set; }
        public int MALOAIMH { get; set; }
        public string TENMH { get; set; }
        public int SOLUONG { get; set; }
        public System.DateTime HANSUDUNG { get; set; }
        public double GIA { get; set; }
        public string DVT { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CTPHIEUNHAP> CTPHIEUNHAPs { get; set; }
        public virtual LOAIMH LOAIMH { get; set; }
    }
}
