//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_QuanLyNhaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.CHITIETORDERs = new HashSet<CHITIETORDER>();
        }
    
        public int MAMONAN { get; set; }
        public string MALOAIMONAN { get; set; }
        public Nullable<int> MAKM { get; set; }
        public string TENMONAN { get; set; }
        public double GIABAN { get; set; }
        public string HINH_MONAN { get; set; }
        public string DVT { get; set; }
        public string TRANGTHAI { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHITIETORDER> CHITIETORDERs { get; set; }
        public virtual KHUYENMAI KHUYENMAI { get; set; }
        public virtual LOAIMONAN LOAIMONAN { get; set; }
    }
}
