//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wpf_QuanLyNhaHang.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SOLUONG_MONAN
    {
        public string TENMONAN { get; set; }
        public Nullable<decimal> SOLUONG { get; set; }
    }
}
